version: 2
jobs:
  update-database-dev:
    working_directory: /tmp/project/
    docker:
      - image: $AWS_ACCOUNT_DEV.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/cicdtools:base-latest
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID_DEV
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY_DEV
    steps:
      - checkout     
      - run:
          name: Update RDS DB with Liquibase
          command: |
            set -e
            echo "Getting started with Update RDS DB with Liquibase..."
            echo "Installing liquibase dependencies..."
            ls -lah && pwd
            ls -lah ./liquibase/
            apt-get -qq update -y && apt-get -qq install -y wget tar default-jre       
            cd ./liquibase && mkdir liquibase && cd liquibase
            wget https://github.com/liquibase/liquibase/releases/download/v4.10.0/liquibase-4.10.0.tar.gz
            tar -xvzf liquibase-4.10.0.tar.gz            
            mv $CIRCLE_WORKING_DIRECTORY/liquibase/liquibase /opt/
            ls -lah /opt/liquibase
            export PATH=$PATH:/opt/liquibase/
            liquibase -version
            echo "Updating DataBase..."
            ls -lah $CIRCLE_WORKING_DIRECTORY/liquibase/ && cd $CIRCLE_WORKING_DIRECTORY/liquibase/
            liquibase status --url="jdbc:postgresql://$VAR_RDS_ENDPOINT_DEV:5432/$VAR_RDS_DB_DEV?currentSchema=public&user=$TFVAR_DBUSER_DEV&password=$TFVAR_DBPASSWORD_DEV" --changeLogFile=app-wrapper.xml --username=$TFVAR_DBUSER_DEV --password=$TFVAR_DBPASSWORD_DEV --classpath=postgresql-42.3.5.jar
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  deploy-python-containerized:
    jobs:
      - update-database-dev